### ISSUE TITLE
Edit Level/Challenge Thumbnails?

### ISSUE THREAD

**Issue by TheLemon27** [IntelOrca/PeggleEdit#11]
I was wondering if there was a way to change the thumbnails that PeggleEdit automatically generates with my own thumbnails? And if not this is a request for you to add a way to do that. Thanks.

**Comment by IntelOrca** [comment]
One workaround is to edit or unpack/repack your .pak file using a seperate tool and edit the thumbnail image.

**Comment by TheLemon27** [comment]
do you have a recommendation for a tool i could use?

**Comment by IntelOrca** [comment]
Export / import pack feature now implemented where the thumbnails can be edited.

**Comment by TheLemon27** [comment]
thank you!

**Comment by TheLemon27** [comment]
wait, how do i change the challenge thumbnails?

**Comment by IntelOrca** [comment]
Right click the level pack in pack explorer, choose export. Edit the images in levels/cached_thumbnails, then re-import the folder.

**Comment by TheLemon27** [comment]
i already did that for the level thumbnails. what im asking is if there is a way i can change the _challenge_ thumbnails, as ive noticed by default the challenges use the thumbnail of the first level in its level list but some challenges in the base game use custom thumbnails, but i can't find any way to do that.
