### ISSUE TITLE
Duel challenges do not load as duels

### ISSUE THREAD

**Issue by Awesome20o** [IntelOrca/PeggleEdit#12]
I made a few duel challenges to share with my friends, but when my friends downloaded and tried to play the challenges, they loaded as normal games. Is this just a bug or do I have to change something in the settings? Thanks

**Comment by IntelOrca** [comment]
I tried creating a challenge and making a duel, the challenge loads with an AI opponent as expected. Is this not what you are experience?

**Comment by Awesome20o** [comment]
I think the issue only arises when I close the editor and/or share the file. When I made a duel and loaded it with the editor open, it loaded as a duel. However, when I re-opened the editor and .pak file, the settings reverted to a normal challenge without a duel triggering. The same happened when I shared the file with others.

**Comment by Awesome20o** [comment]
I think I know the problem now, each duel setting corresponds to the next difficulty (Easy in the editor is Normal in-game, Normal is Hard, etc.) so Master duels just break entirely because there's no next difficulty.
