### ISSUE TITLE
Line Generator

### ISSUE THREAD

**Issue by YoYoBobbyJoe** [IntelOrca/PeggleEdit#13]
I would love to see a line generator in the editor at some point; brick straight lines are hard to make without it. In a perfect world, it would be a point, path, and curve system like in Illustrator, but I know nobody has the time to program for something like Peggle. 

On another note, it's awesome to see that you've come back to work on this project more! The Peggle community really appreciates it.

**Comment by IntelOrca** [comment]
A lot more brick tools are now available including a bezier curve tool, and brick snapping.
