### ISSUE TITLE
Invalid Save Game load error

### ISSUE THREAD

**Issue by cudsys** [IntelOrca/PeggleEdit#17]
When I try to load certain custom levels I've made, I get this load error (shown in image below). I don't know what causes it but the only fix I've been able to find is remaking the whole level again. I've also attached the level in question.

[hi there.zip](https://github.com/IntelOrca/PeggleEdit/files/12614112/hi.there.zip)

![image](https://github.com/IntelOrca/PeggleEdit/assets/116428521/21f60044-d374-459d-b315-327cfc0a6e53)

**Comment by cudsys** [comment]
I should also mentioned that I've read the documentation. All generators have been applied and such.

**Comment by IntelOrca** [comment]
![image](https://github.com/IntelOrca/PeggleEdit/assets/1482259/89ad0d59-f081-4648-8713-f9ce9cfba435)
