### ISSUE TITLE
Polygons

### ISSUE THREAD

**Issue by PeggleM** [IntelOrca/PeggleEdit#7]
Hey there!

First of all, thanks for creating such a wonderful tool. I've been trying to do some levels of Peggle 2 on it to play them on Peggle Nights -- but I got a huge problem while creating an object.

For some reason, the polygon does not project the image i wanted it to show -- and worst, the points seem to be open in-game.

I attached two images of the problem.
How do I make this work? Please help :(

![1](https://user-images.githubusercontent.com/64550940/80628272-7cc71180-8a27-11ea-9e5c-40470dfab012.png)
![2](https://user-images.githubusercontent.com/64550940/80628294-86507980-8a27-11ea-886e-10678e9cbb0a.png)

**Comment by IntelOrca** [comment]
Polygon points must be defined anti-clockwise. The images look like they have been loaded.
