### ISSUE TITLE
Empty Space

### ISSUE THREAD

**Issue by imaperson1060** [IntelOrca/PeggleEdit#8]
I'm not that great at explaining things but I'll give this my best shot. Basically I tried importing a picture (for the background) that wasn't as tall as the borders. When I opened the level, it worked but anything passing over the empty space left an imprint. Like the free ball bucket, the ball itself, or any text. Can you add a way to resize the background so I can use any picture without manually resizing it?

**Comment by YoYoBobbyJoe** [comment]
I think the documentation should just include a blurb on backgrounds that the ideal image size is 800x600.

**Comment by IntelOrca** [comment]
The editor will now automatically resize the image to fit the canvas as best as possible.
